apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: vkpaints-dev-ns
data:
  RABBITMQ_URL: "amqp://rabbitmq"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_SECURE: "false"
