apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deploy
  namespace: vkpaints-dev-ns
spec:
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-container
        image: shubha20/vk-paints_notification-service:v1.0.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: notification-config
        - secretRef:
            name: notification-secret
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10

        - containerPort: 3000
